input {
  kafka {
    bootstrap_servers => "kafka:29092"
    topics => ["service-logs"]
    codec => "json"
    consumer_threads => 1
    group_id => "logstash"
    auto_offset_reset => "earliest"
  }
}

filter {
  if [message] =~ "/actuator/" {
    drop {}
  }

  # amount 문자열 → 숫자 변환 (Kibana 평균 집계용)
  if [amount] {
    mutate {
      convert => { "amount" => "integer" }
    }
  }

  mutate {
    remove_field => ["@version", "event"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "service-logs-%{+YYYY.MM.dd}"
  }
}
